import type { Metadata } from "next";
import "./styles/globals.scss";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AOSInitializer from "./components/AOSInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body>
        <AOSInitializer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}